# Generated by Django 2.0.1 on 2018-02-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantMoisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('moisture_voltage', models.IntegerField()),
                ('time_measured', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
